name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
    
    - name: Build
      run: xcodebuild build -scheme todolist -sdk iphonesimulator
    
    - name: Run Tests
      run: xcodebuild test -scheme todolist -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max,OS=latest' CODE_SIGNING_ALLOWED='NO' -enableCodeCoverage YES -resultBundlePath TestResults.xcresult -verbose
    
    - name: Generate Coverage Report
      run: |
        xcrun xcresulttool get --format json --path TestResults.xcresult > coverage.json
        echo "<html><body><pre>" > coverage.html
        cat coverage.json | jq '.issues.coverage' >> coverage.html
        echo "</pre></body></html>" >> coverage.html
    
    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: |
          TestResults.xcresult
          coverage.json
          coverage.html
